// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ig2uOSO6xoh0IkMiFgoH0_k9neItGKk',
    appId: '1:582768991231:ios:df7530bb408acdf4fca5ca',
    messagingSenderId: '582768991231',
    projectId: 'music-diary-cb85e',
    storageBucket: 'music-diary-cb85e.firebasestorage.app',
    iosBundleId: 'com.nazarsokalchuk.musicDiary',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5-Vx4YNK6uL7maKzYQsvZnokXGc7D8Fg',
    appId: '1:582768991231:web:655906a1799a18e3fca5ca',
    messagingSenderId: '582768991231',
    projectId: 'music-diary-cb85e',
    authDomain: 'music-diary-cb85e.firebaseapp.com',
    storageBucket: 'music-diary-cb85e.firebasestorage.app',
    measurementId: 'G-6GRP5Z22VS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ig2uOSO6xoh0IkMiFgoH0_k9neItGKk',
    appId: '1:582768991231:ios:2eb89e08de6f2b0dfca5ca',
    messagingSenderId: '582768991231',
    projectId: 'music-diary-cb85e',
    storageBucket: 'music-diary-cb85e.firebasestorage.app',
    iosBundleId: 'com.example.musicDiary',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3HPZeoB5xStMfhz6ZenjqLnkrbC3X1Jw',
    appId: '1:582768991231:android:2d901f378caf90e6fca5ca',
    messagingSenderId: '582768991231',
    projectId: 'music-diary-cb85e',
    storageBucket: 'music-diary-cb85e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5-Vx4YNK6uL7maKzYQsvZnokXGc7D8Fg',
    appId: '1:582768991231:web:627a9ca2f20cb665fca5ca',
    messagingSenderId: '582768991231',
    projectId: 'music-diary-cb85e',
    authDomain: 'music-diary-cb85e.firebaseapp.com',
    storageBucket: 'music-diary-cb85e.firebasestorage.app',
    measurementId: 'G-6G74C4PWWG',
  );

}